#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def render(version: str, arm_sha: str, intel_sha: str) -> str:
    return f'''# This file was generated by the agent-insights release workflow. DO NOT EDIT.
cask "agent-insights-cli" do
  version "{version}"

  on_macos do
    on_arm do
      sha256 "{arm_sha}"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{{version}}/agent-insights_#{{version}}_darwin_arm64.tar.gz"
    end

    on_intel do
      sha256 "{intel_sha}"
      url "https://github.com/tomnagengast/agent-insights/releases/download/v#{{version}}/agent-insights_#{{version}}_darwin_amd64.tar.gz"
    end
  end

  name "agent-insights-cli"
  desc "CLI for generating AI agent session insights reports."
  homepage "https://github.com/tomnagengast/agent-insights"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-insights"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{{staged_path}}/agent-insights"]
    end
  end

  caveats <<~EOS
    Requires authenticated `claude` on PATH for facet and report generation.
  EOS
end
'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Render the agent-insights Homebrew cask.")
    parser.add_argument("output", type=Path)
    parser.add_argument("version")
    parser.add_argument("arm_sha")
    parser.add_argument("intel_sha")
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.version, args.arm_sha, args.intel_sha))


if __name__ == "__main__":
    main()
